import React from 'react';

export default function Reports(){
  return (
    <div className="container">
      <div className="card">
        <h2>📄 Reports</h2>
        <p>PDF reports are generated by the Python backend. Click generate to request a PDF.</p>
      </div>
    </div>
  )
}
